dist: trusty
sudo: required
language: node_js
node_js:
- '7'

services:
  - docker

before_script:
  - npm run build

branches:
  only:
  - master
  - ekult

script:
    - docker login --username=_ --password=$(echo $API_KEY) registry.heroku.com
    - docker build -t registry.heroku.com/fastball-dev/web .
    - docker push registry.heroku.com/fastball-dev/web

